### ISSUE TITLE
piholeBlockratePerClient.sh should also order by clientname, rate, …

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/files#1]
Hi @hagezi , that's really a great script! ❤️  
Did you already think about adding some sort-options as parameter? If you want/like, I can do an PR for this…
<details>
<pre>
ip              clientname           blocked  allowed  rate
--------------  -------------------  -------  -------  ----
172.21.0.1                           17342    1815676  0
192.168.42.101                                21
192.168.42.107                                12
192.168.42.108                                16
192.168.42.109                                15
192.168.42.110                       4        32       12
192.168.42.111                                14
192.168.42.112                                9
192.168.42.113                       5        378      1
192.168.42.114                       4        39       10
192.168.42.115                       2        30       6
192.168.42.116                                17
192.168.42.119                       2        27       7
192.168.42.120                                11
192.168.42.121                                20
192.168.42.122                                15
192.168.42.124                                30
192.168.42.126                                18
192.168.42.127                       12306    54402    22
192.168.42.128                       4        32       12
192.168.42.129                                23
192.168.42.131                                28
192.168.42.132                                13
192.168.42.133                                26
192.168.42.134                                5
192.168.42.135                                20
192.168.42.138                                6
192.168.42.139                                26
192.168.42.140                                9
192.168.42.141                       2046     6380     32
192.168.42.143                       2116     4752     44
192.168.42.144                       97500    290580   33
192.168.42.146                                62
192.168.42.148                       10       49       20
192.168.42.149                       682      1854     36
192.168.42.150                                22
192.168.42.151                       2        20       10
192.168.42.152                                8
192.168.42.153                                13
192.168.42.154                                10
192.168.42.158                       40       26       153
192.168.42.159                       16       113      14
192.168.42.161                                57
192.168.42.162                                19
192.168.42.163                                9
192.168.42.164                       80412    232598   34
192.168.42.167                                90
192.168.42.168                                10
192.168.42.169                                17
192.168.42.170                                16
192.168.42.172                                23
192.168.42.174                                9
192.168.42.176                       270      526      51
192.168.42.177                                37
192.168.42.178                                10
192.168.42.180                                31
192.168.42.182                                20
192.168.42.185                                47
192.168.42.186                                9
192.168.42.187                                26
192.168.42.188                                20
192.168.42.189                                4
192.168.42.190                       32       80       40
192.168.42.191                                10
192.168.42.192                                12
192.168.42.193                                19
192.168.42.196                                30
192.168.42.197                       7536     15664    48
192.168.42.198                                42
192.168.42.201                       71       112      63
192.168.42.202                       150      519      28
192.168.42.203                       4        32       12
192.168.42.206                                30
192.168.42.207                                12
192.168.42.208                                28
192.168.42.209                                17
192.168.42.210                                6
192.168.42.211                                5
192.168.42.212                                12
192.168.42.213                                6
192.168.42.214                                4
192.168.42.216                       2        10       20
192.168.42.218                       64       266      24
192.168.42.221                       12252    85582    14
192.168.42.222                       134      1026     13
192.168.42.223                       81       387      20
192.168.42.224                                52
192.168.42.225                                12
192.168.42.226                                16
192.168.42.227                                5
192.168.42.228                                14
192.168.42.229                                19
192.168.42.230                                4
192.168.42.231                                11
192.168.42.233                       2        14       14
192.168.42.235                                3978
192.168.42.236                                28
192.168.42.238                       2        14       14
192.168.42.239                       11420    109982   10
192.168.42.240                       266      1136     23
192.168.42.243                       2        49       4
192.168.42.244                                11
192.168.42.245                       2        20       10
192.168.42.246                                17
192.168.42.248                                24
…
</pre>
</details>

**Comment by hagezi** [comment]
You can take over with pleasure ;)

**Comment by thomasmerz** [comment]
@yubiuser this Repo over here could also be of interest for your https://github.com/yubiuser/pihole_tools or https://github.com/yubiuser/pihole_adlist_tool

**Comment by thomasmerz** [comment]
Still didn't find any time to work on this… 😞

**Comment by thomasmerz** [comment]
I'm confused regarding the "rate" column - 226% blocked-rate? 😜 
```
ip              clientname           blocked  allowed  rate
--------------  -------------------  -------  -------  ----
…
192.168.42.158                       68       30       226
```

**Comment by hagezi** [comment]
great block performance. ;)

**Comment by thomasmerz** [comment]
> great block performance. ;)


Haha 🤣 But I think there's some miscalculation in the rate.
Please have a look at another PR: https://github.com/hagezi/files/pull/6

**Comment by hagezi** [comment]
Yes, thanks.
