### ISSUE TITLE
exportPiholeQueryLog.sh: wrong result(s) for blockedblack

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/files#11]
I try to understand and still investigate why `www.netzwelt.de` has been found by one of these queries:
```
pihole/exportPiholeQueryLog.sh
36:blockedblack=$output/blocked.blacklist.txt
44:sqlite3 "$piholedb" "SELECT DISTINCT domain FROM queries WHERE type IN (1,2) AND status IN(4,5,10,11) ORDER BY domain;" >>"$blockedblack"
45:sqlite3 "$piholedb" "SELECT DISTINCT additional_info FROM queries WHERE type IN (1,2) AND status IN(10,11) ORDER BY additional_info;" >>"$blockedblack"
```
```
$ sqlite3 "$piholedb" "SELECT DISTINCT * FROM queries WHERE type IN (1,2) AND status IN(4,5,10,11) and domain like '%netzwelt.de' ORDER BY domain;"
30956102|1669844027|1|10|www.netzwelt.de|192.168.42.105|94.140.14.14#53|http2.netzwelt.map.fastly.net|3|0.035|2
30956103|1669844027|2|10|www.netzwelt.de|192.168.42.105|94.140.14.14#53|http2.netzwelt.map.fastly.net|3|0.0333|2
```
Because `www.netzwelt.de` is (currently) not on my blocklist it shouldn't be found therefore… 🤔

**Comment by hagezi** [comment]
`www.netzwelt.de` CNAME `http2.netzwelt.map.fastly.net` ;)
CNAME is blocked in your lists or in 94.140.14.14

**Comment by thomasmerz** [comment]
Ah, many thanks! Now I "remember" this CNAME stuff:
> Pi-hole unterstützt die dafür notwendige deep CNAME inspection seit 2020 ab Version [Pi-hole 5 6](https://discourse.pi-hole.net/t/pi-hole-v5-0-is-here/31843)

https://discourse.pi-hole.net/t/pi-hole-und-cname-cloaking/54123/2

How do you come to `94.140.14.14`? Have you been reading https://thomasmerz.github.io/pihole-wireguard-knowhow/ ? 😃

**Comment by hagezi** [comment]
`94.140.14.14` is the free AdGuardDNS ...
