### ISSUE TITLE
🛂 Teleporter-Backup should not be made public available

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/files#16]
I had a look in your Teleporter-Backup, searching for some tweaks or settings that might enhance my Pihole installation. But I found some **sensible data** that you might not want to be made public available!?
- WEBPASSWORD for your Pi-hole
- hostnames which gives an interesting insight of your infrastructure, smart home, gaming, TVs and family…

**Comment by hagezi** [comment]
LOL, thanks, is not a big deal, but I would have to delete the repository now to remove this completely, right?

**Comment by thomasmerz** [comment]
But what I found… as you are also an Apple user but you're **not using any apple-blocklist** as I do which results in this [Adlist coverage](https://github.com/yubiuser/pihole_adlist_tool) which shows that Apple is doing a lot/much/the most block-able stuff I've ever seen! 😢 

```
id  enabled  total_domains  domains_covered  hits_covered  unique_domains_covered  address
--  -------  -------------  ---------------  ------------  ----------------------  --------------------------------------------------------------------------------------------------------
83  1        234            69               236302        56                      https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry
(12 lines deleted)
95  1        22             10               9398                                  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.apple.txt
```

And the "Top 20 blocked adlist domains" since the last 30 days:
```
domain                              hits
----------------------------------  -----
gs-loc.apple.com                    38535
api.smoot.apple.com                 25697
cl4.apple.com                       24874
gsp64-ssl.ls.apple.com              20065
cl3.apple.com                       17713
iphone-ld.apple.com                 14831
app-measurement.com                 11853 # common SDK on iOS with tracking
pancake.apple.com                   11665
gsp-ssl.ls.apple.com                10460
configuration.ls.apple.com          9138
cl1.apple.com                       8849
dit.whatsapp.net                    8527
metrics.icloud.com                  5964
gsp85-ssl.ls.apple.com              5948
stats.gc.apple.com                  5778
xp.apple.com                        5571
firebaselogging-pa.googleapis.com   5419
device-provisioning.googleapis.com  5258
s.youtube.com                       5093
googleads.g.doubleclick.net         4457
```

**Comment by thomasmerz** [comment]
> delete the repository now to remove this completely

No, you could also do this without removing/deleting the whole repo by removing the teleporter-backup-file and do a `git rebase "$(git rev-list HEAD | tail -n1)" && git push -f`.

Or: 
- just delete the file
- change secret (if your family is also reading here and have access to your local Pi-hole 😉 )
- forget about the hostnames

---

⚠️  But please try/train with a different local copy!

**Comment by hagezi** [comment]
If you do not want to restrict the function of an Apple device, the following remains as blockable:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt

**Comment by thomasmerz** [comment]
My/our apple devices (9) are functioning well with both blocklists. You should try with a "testing-group" in your Pi-hole with your devices only. That's the way I make a new blocklist active for all devices.

**Comment by hagezi** [comment]
You know what you are blocking with which Apple domain for services or is this more of a try and error blocking?

**Comment by thomasmerz** [comment]
Solution for this issue might be [this](https://stackoverflow.com/a/58497525)
```
git update-ref -d HEAD
git push origin main -f
```
See: https://github.com/thomasmerz/fork-hagezi-files/tree/new_main

**Comment by thomasmerz** [comment]
Regarding apple-blocklist:
When I started using it this list was actively maintained, but now it seems [orphaned](https://github.com/liamengland1/mischosts/pull/30#issuecomment-1345520083). So currently it's still working for all my family's devices, but you are right: currently it's more on a try&error base than a curated list 😢 But it's working for me/us quite well since so many years with all these stable entries 😉

**Comment by thomasmerz** [comment]
Regarding apple-blocklist:
When I started using it this list was actively maintained, but now it seems [orphaned](https://github.com/liamengland1/mischosts/pull/30#issuecomment-1345520083). So currently it's still working for all my family's devices, but you are right: currently it's more on a try&error base than a curated list 😢 But it's working for me/us quite well since so many years with all these stable entries 😉

**Comment by hagezi** [comment]
> Solution for this issue might be [this](https://stackoverflow.com/a/58497525)
> 
> ```
> git update-ref -d HEAD
> git push origin main -f
> ```
> 
> See: https://github.com/thomasmerz/fork-hagezi-files/tree/new_main

```
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/hagezi/files.git'
```

**Comment by thomasmerz** [comment]
I checked all my blocked apple domains with https://support.apple.com/en-us/HT210060 which I used for reference in https://github.com/cedws/apple-telemetry/issues/27:
Only `xp.apple.com` (blocked 5571 times) should not be blocked for "Software updates" (without a description!?) and I can confirm that both (private and enterprise managed iphones and ipads and watches) are working just as expected 🤷🏼‍♂️

**Comment by hagezi** [comment]
If you use the location service to find a device or share a location, you should not block `gs-loc.apple.com` either .... just an example. It doesn't matter, if it suits you it's ok.

**Comment by thomasmerz** [comment]
Strange, you sound so absolutely right. But this is so confusing because I can find my iphone… 🤷🏼‍♂️ 
<img width="137" alt="grafik" src="https://user-images.githubusercontent.com/18568381/236894524-76597474-bf06-441f-a378-7903ef9755ab.png">

**Comment by thomasmerz** [comment]
> main does not match

Are you still interested in fixing without a "reset"? This looks much harder than I thought… 😱

**Comment by hagezi** [comment]
> Are you still interested in fixing without a "reset"? This looks much harder than I thought… 😱

Yes, but if a re-init is necessary, then so be it. Haven't found a solution either. Although would an init really be enough? I don't think so, it should still be in your fork then, right?

**Comment by thomasmerz** [comment]
Yes, all forks will still have your old data. So maybe it's sufficient to change secret, delete files and "done". I think nobody can do something evil with your data. But I really wanted to tell you that you shouldn't upload this on GitHub.

**Comment by hagezi** [comment]
Used https://rtyley.github.io/bfg-repo-cleaner/ to delete the file ...

**Comment by thomasmerz** [comment]
Can you explain in short what you did in detail (for documentation and knowhow-transfer)? Thanks a lot!

**Comment by hagezi** [comment]
![grafik](https://user-images.githubusercontent.com/104343908/236922345-c39b7b90-4ad4-47a0-b224-baf8081605cd.png)

it's on the bfg website ...
