### ISSUE TITLE
updateUnboundBlacklist.sh pulling empty file

### ISSUE THREAD

**Issue by rhy7s** [hagezi/files#18]
I have been using cron with updateUnboundBlacklist.sh to keep multi.blacklist.conf up to date and it had been working fine in the past but looking there now I see the file is empty, what is the URL format I should be using?

**Comment by hagezi** [comment]
The script is obdolete, the lists are only available for Unbound in the RPZ format, see:

https://github.com/hagezi/dns-blocklists/issues/3127
