### ISSUE TITLE
exportPiholeQueryLog.sh doesn't need dos2unix when running Pi-hole on Linux

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/files#2]
Why do you need `dos2unix`? Pi-hole normally runs on a linux distribution or in a linux docker container. To prevent this (running Pi-hole in docker on my openSUSE/Ubuntu) you should not need to use `dos2unix`:
```
root@pihole-merz-nimbus:/etc/pihole# ./exportPiholeQueryLog.sh exportPiholeQueryLog
sudo: dos2unix: command not found
sudo: dos2unix: command not found
sudo: dos2unix: command not found
```

**Comment by hagezi** [comment]
Yes, that's right, in that case it's not necessary.

**Comment by thomasmerz** [comment]
PR or will you clean this? I'm not aware what were your thoughts when you did code this…

**Comment by hagezi** [comment]
I had once edited the exported lists via Sambashare with a windows editor to throw out domains, so the dos2unix was in there.

**Comment by thomasmerz** [comment]
Follow-up: have a look [here](https://github.com/hagezi/files/blob/main/pihole/exportPiholeQueryLog.sh#L16)
