### ISSUE TITLE
Very long running SQLs in exportPiholeQueryLog.sh

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/files#3]
These queries run "much too long" - why?
```
sqlite3 'SELECT DISTINCT domain FROM queries WHERE type IN (1,2) AND status IN(4,5,10,11) ORDER BY domain;'
sqlite3 'SELECT DISTINCT additional_info FROM queries WHERE type IN (1,2) AND status IN(10,11) ORDER BY additional_info;'
```
I aborted this after 19 minutes still running… 😞  My `pihole-FTL.db` has a size of 491 MB keeping 100 days (`MAXDBDAYS=100` in `pihole-FTL.conf`).

When I find some time the next days I will do some more long-running "performance testing"…  

What are your experiences and running times with which DB size?

**Comment by hagezi** [comment]
I tested it with 30 days and it worked. Take out the order by and try again.

**Comment by hagezi** [comment]
Instead of distinct, you could also try group by. But the execution plan should be almost identical.

**Comment by thomasmerz** [comment]
Still didn't find any time to work on this… 😞

**Comment by thomasmerz** [comment]
I dont't know what happened, but it's not slow any more 🤷🏼‍♂️ 
```
🦎🖥  ✔ ~/temp/PRs/fork-hagezi-files [main|…6]
19:43 $ time sudo pihole/exportPiholeQueryLog.sh . ~thomas/dev/docker-pi-hole/etc-pihole/pihole-FTL.db

real	0m3.533s
user	0m3.193s
sys	0m0.337s
```
